name: Python application

on:
  push:
    branches: [ "**" ]  # Runs on all branches
  pull_request:
    branches: [ "**" ]  # Runs on all branches

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      working-directory: ./app_python 
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      working-directory: ./app_python  
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      working-directory: ./app_python
      run: |
        pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      working-directory: ./app_python
      run: |
        docker build -t your-dockerhub-username/your-repo-name:latest .

    - name: Push Docker image
      working-directory: ./app_python 
      run: |
        docker push your-dockerhub-username/your-repo-name:latest
